### PR TITLE
Revert "Add a http-command-service as an example"

### PR DESCRIPTION
**Pull request by davidmsh**
Reverts edgexfoundry-holding/app-functions-azure#3

### CODE REVIEW

**Comment by lenny-intel** [comment]
@davidmsh , you need to sign-off on your commit.

**Comment by davidmsh** [comment]
@lenny-intel The revert change is generated by github, not sure exactly how i can do a sign-off. While I can try to find out how but there are 3 commits to revert, is it possible for someone to do a reset locally and do a "git push -f" ?
We shall roll back to commit 655514e46700d3891fd02fc9a2f1c45c8765417a

**Comment by lenny-intel** [comment]
@davidmsh , no worries. With the decision to move to a single examples repo, this will fit in as is when it is moved to the new repo.

**Comment by lenny-intel** [comment]
@davidmsh , we have created the new examples repo. Please feel free to add you example to https://github.com/edgexfoundry-holding/app-service-examples under the `app-services` folder.

**Pull request merged**
