### PR TITLE
Add a http-command-service as an example

### PR DESCRIPTION
**Pull request by davidmsh**
Add a http-command-service as an example to expose certain edgex command as a http service.

### CODE REVIEW

**Comment by lenny-intel** [comment]
@davidmsh. Why was this added to Azure repo when it has nothing to do with Azure?

**Comment by rsdmike** [comment]
Hey @davidmsh , we appreciate the contribution. However, this is not the right place for this example as it should be along with the rest of the SDK examples since this doesn't have anything to do with Azure. Also, despite this being in the EdgeX Foundry Holding organization, we still would like to adhere to best practices requiring that at the very least, one reviewer approves the PR.  With that being said, can you please revert your changes to remove these commits and we'll find a better place for the example to live.

**Comment by davidmsh** [comment]
@lenny-intel ya, it's not directly related to Azure but it's something coming out my work to integrate with Azure's direct method calling into Edgex so thought it will be a good example. Will try to find another place for it.
@rsdmike will revert it

**Comment by lenny-intel** [comment]
@davidmsh , we plan to put the `where to put examples` topic on this week's App Service WG meeting agenda.

**Comment by davidmsh** [comment]
@lenny-intel Thanks for the heads-up, I will see if I can attend the call

**Comment by davidmsh** [comment]
@lenny-intel I watched the recording so we are going with the decision that we create a repo in the holding area and have pointers in README in SDK repos pointing to them ? Instead we add more "examples" to the SDK itself ?
@cloudxxx8

**Comment by davidmsh** [comment]
@lenny-intel @rsdmike Some more thoughts, although this piece of work is not work specifically for Azure but it did come from my work trying to integrate EdgeX with Azure IoT. If I include the whole scenario in README it will be very useful for people trying to use Azure which is quite valuable. The whole repos can serve as one top site for things integrating with Azure. Or we want to disperse those smaller "examples" here and there and have them maintained separately. These are just examples, people want integrate with, say AWS. can reference the Azure examples and have there similar "examples" tailored to their needs that's probably fine too. I mean the repos is a more complete example for a specific cloud vendor. 
Just some thoughts.
@cloudxxx8

**Comment by lenny-intel** [comment]
@davidmsh, we have made the decision to move all examples into a new (to be created) `examples` repo. This will allow all examples, SDK, Azure, AWS, etc. to be in one place.

**Comment by judehung** [comment]
@lenny-intel , could you please let me know where I could find the `examples` repo as mentioned in your previous comment?

**Comment by lenny-intel** [comment]
@judehung , @rsdmike just created the https://github.com/edgexfoundry-holding/app-service-examples repo yesterday. I will be create the folder structure and moving the examples from the SDK into this repo today.

**Pull request merged**
